# Public-release copy: file paths were converted to repository-relative paths.
# Statistical logic, parameters, thresholds, and seeds are unchanged from the archived final script.
script_dir <- dirname(normalizePath(sub("^--file=", "", grep("^--file=", commandArgs(), value=TRUE)[1]))); source(file.path(dirname(script_dir), "02_singlecell_preprocessing", "common.R"))
suppressPackageStartupMessages(library(lme4))
x<-read_corrected();m<-x$metadata;m$GART_status<-relevel(factor(m$GART_status),"negative");m$cohort<-factor(m$cohort);m$donor_id<-factor(m$donor_id);m$sample_id<-factor(m$sample_id);m$log_nUMI<-log1p(m$nCount_RNA)
mods<-names(x$public_gene_sets);eff<-list();paired_rows<-list();pair_data<-list();diag<-list()
for(nm in mods){d<-m;d$outcome<-zwithin(d[[nm]],d$cohort)
 for(st in c("donor-only","donor/sample")){ff<-if(st=="donor-only")outcome~GART_status+scale(log_nUMI)+scale(nFeature_RNA)+S_score+G2M_score+cohort+(1|donor_id) else outcome~GART_status+scale(log_nUMI)+scale(nFeature_RNA)+S_score+G2M_score+cohort+(1|donor_id/sample_id);q<-capture_fit(lmer(ff,data=d,REML=FALSE));eff[[length(eff)+1]]<-fit_effect(q$fit,"GART_statuspositive",nm,st,nrow(d),length(unique(d$donor_id)),q$warning)}
 ag<-aggregate(d[[nm]],list(donor_id=d$donor_id,cohort=d$cohort,GART_status=d$GART_status),mean);names(ag)[4]<-"mean_score";w<-reshape(ag,idvar=c("donor_id","cohort"),timevar="GART_status",direction="wide");w$delta<-w$mean_score.positive-w$mean_score.negative;w$module<-nm;pair_data[[length(pair_data)+1]]<-w;tt<-t.test(w$delta);paired_rows[[length(paired_rows)+1]]<-data.frame(module=nm,n_paired_donors=sum(is.finite(w$delta)),mean_delta=mean(w$delta,na.rm=TRUE),CI_low=tt$conf.int[1],CI_high=tt$conf.int[2],paired_t_P=tt$p.value,paired_Wilcoxon_P=wilcox.test(w$delta,exact=FALSE)$p.value)
}
e<-do.call(rbind,eff);e$FDR<-ave(e$P,e$random_structure,FUN=function(v)p.adjust(v,"BH"));write.csv(e,file.path(output_root,"RESULTS","primary_module_mixed_models.csv"),row.names=FALSE);write.csv(do.call(rbind,paired_rows),file.path(output_root,"RESULTS","primary_module_paired_donor_tests.csv"),row.names=FALSE);write.csv(do.call(rbind,pair_data),file.path(output_root,"RESULTS","primary_module_paired_donor_data.csv"),row.names=FALSE)
params<-read.csv(file.path(singlecell_root, "MODULE_GENE_SETS_AND_PARAMETERS.csv"));write.csv(params,file.path(output_root,"AUDIT","singlecell_module_gene_sets_and_parameters.csv"),row.names=FALSE)
phase<-ifelse(m$S_score<0&m$G2M_score<0,"G1",ifelse(m$S_score>=m$G2M_score,"S","G2M"));strat<-list();for(nm in mods)for(ph in c("G1","S","G2M")){d<-m[phase==ph,];d$outcome<-zwithin(d[[nm]],d$cohort);q<-capture_fit(lmer(outcome~GART_status+scale(log_nUMI)+scale(nFeature_RNA)+cohort+(1|donor_id),data=d,REML=FALSE));strat[[length(strat)+1]]<-fit_effect(q$fit,"GART_statuspositive",paste(nm,ph,sep="::"),"donor-only",nrow(d),length(unique(d$donor_id)),q$warning)};ss<-do.call(rbind,strat);ss$module<-sub("::.*$","",ss$analysis);ss$phase<-sub("^.*::","",ss$analysis);ss$FDR<-ave(ss$P,ss$phase,FUN=function(v)p.adjust(v,"BH"));write.csv(ss,file.path(output_root,"RESULTS","module_cell_cycle_stratified.csv"),row.names=FALSE)
