# Public-release copy: file paths were converted to repository-relative paths.
# Statistical logic, parameters, thresholds, and seeds are unchanged from the archived final script.
script_dir <- dirname(normalizePath(sub("^--file=", "", grep("^--file=", commandArgs(), value=TRUE)[1]))); source(file.path(dirname(script_dir), "02_singlecell_preprocessing", "common.R"))
suppressPackageStartupMessages({library(SeuratObject);library(lme4);library(Matrix)})
obj<-readRDS(file.path(singlecell_root,"UC_GART_07_ISC_like_subclustered_FIXED_withDonor.rds"));m<-read_corrected()$metadata;a<-obj[["RNA"]];genes<-c("PPAT","GART","PFAS","PAICS","ADSL","ATIC")
layer_full<-function(ln){z<-methods::slot(a,"layers")[[ln]];fn<-methods::slot(a,"features")[[ln]];cn<-methods::slot(a,"cells")[[ln]];if(is.null(dim(z)))z<-matrix(z,nrow=length(fn),ncol=length(cn));if(is.null(rownames(z)))rownames(z)<-fn;if(is.null(colnames(z)))colnames(z)<-cn;z}
raw<-matrix(NA_real_,length(genes),nrow(m),dimnames=list(genes,rownames(m)));expr<-raw
for(type in c("counts","data"))for(ln in grep(paste0("^",type),Layers(a),value=TRUE)){z<-layer_full(ln);g<-intersect(genes,rownames(z));if(type=="counts")raw[g,colnames(z)]<-as.matrix(z[g,,drop=FALSE]) else expr[g,colnames(z)]<-as.matrix(z[g,,drop=FALSE])}
m$condition<-relevel(factor(m$condition),"Healthy");m$cohort<-factor(m$cohort);m$donor_id<-factor(m$donor_id);m$sample_id<-factor(m$sample_id);m$log_nUMI<-log1p(m$nCount_RNA);res<-list();diag<-list();don<-list()
for(g in genes){m$det<-as.integer(raw[g,]>=1);m$pos_expr<-expr[g,];d<-m[complete.cases(m[,c("det","condition","cohort","donor_id","sample_id","log_nUMI","nFeature_RNA","S_score","G2M_score")]),];q<-capture_fit(glmer(det~condition+scale(log_nUMI)+scale(nFeature_RNA)+S_score+G2M_score+cohort+(1|donor_id),d,family=binomial(),control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))));res[[paste0(g,"_det")]]<-fit_effect(q$fit,"conditionUC",paste(g,"detection"),"donor-only",nrow(d),length(unique(d$donor_id)),q$warning);p<-d[d$det==1&is.finite(d$pos_expr),];q2<-capture_fit(lmer(pos_expr~condition+scale(log_nUMI)+scale(nFeature_RNA)+S_score+G2M_score+cohort+(1|donor_id),p,REML=FALSE));res[[paste0(g,"_pos")]]<-fit_effect(q2$fit,"conditionUC",paste(g,"positive expression"),"donor-only",nrow(p),length(unique(p$donor_id)),q2$warning);ag<-aggregate(d$det,list(cohort=d$cohort,condition=d$condition,donor_id=d$donor_id),mean);names(ag)[4]<-"detection_fraction";ag$gene<-g;don[[g]]<-ag}
r<-do.call(rbind,res);r$gene<-sub(" .*","",r$analysis);r$model_part<-ifelse(grepl("positive",r$analysis),"positive_expression","detection");r$FDR<-ave(r$P,r$model_part,FUN=function(v)p.adjust(v,"BH"));write.csv(r,file.path(output_root,"RESULTS","purine_enzyme_adjusted_models.csv"),row.names=FALSE);write.csv(do.call(rbind,don),file.path(output_root,"RESULTS","purine_enzyme_donor_detection.csv"),row.names=FALSE);write.csv(data.frame(gene=genes,raw_missing_cells=rowSums(is.na(raw)),normalized_missing_cells=rowSums(is.na(expr))),file.path(output_root,"AUDIT","purine_layer_completeness.csv"),row.names=FALSE)
