# Public-release portability repair.
# Scientific code restored from authoritative final-analysis source: 02_SINGLECELL_REANALYSIS_REVISED/CODE/05_pseudobulk_DEG_GSEA.R
# Only path/input/output handling, missing-input messages, and clearly corrupted redaction strings were changed.
script_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
if (!length(script_arg)) stop("Run this script with Rscript so the repository root can be resolved.", call. = FALSE)
script_file <- normalizePath(sub("^--file=", "", script_arg[[1]]), winslash = "/", mustWork = FALSE)
script_dir <- dirname(script_file)
source(file.path(dirname(script_dir), "path_config.R"))
paths <- gart_paths(script_file)
source(file.path(dirname(script_dir), "02_singlecell_preprocessing", "common.R"))
suppressPackageStartupMessages({library(SeuratObject);library(Matrix);library(edgeR);library(fgsea)})
obj<-readRDS(file.path(singlecell_root,"UC_GART_07_ISC_like_subclustered_FIXED_withDonor.rds"));meta<-read_corrected()$metadata;a<-obj[["RNA"]]
layer_full<-function(ln){z<-methods::slot(a,"layers")[[ln]];fn<-methods::slot(a,"features")[[ln]];cn<-methods::slot(a,"cells")[[ln]];if(is.null(dim(z)))z<-matrix(z,nrow=length(fn),ncol=length(cn));if(is.null(rownames(z)))rownames(z)<-fn;if(is.null(colnames(z)))colnames(z)<-cn;z}
ln<-grep("^counts\\.SCP",Layers(a),value=TRUE)[1];mat<-layer_full(ln);mm<-meta[colnames(mat),,drop=FALSE]
run_pb<-function(threshold){tab<-table(mm$donor_id,mm$GART_status);ok<-rownames(tab)[tab[,"negative"]>=threshold&tab[,"positive"]>=threshold];sel<-mm$donor_id%in%ok;md<-mm[sel,,drop=FALSE];cm<-mat[,rownames(md),drop=FALSE];grp<-factor(paste(md$donor_id,md$GART_status,sep="__"));Z<-sparse.model.matrix(~0+grp);pb<-cm%*%Z;colnames(pb)<-sub("^grp","",colnames(Z));sm<-do.call(rbind,strsplit(colnames(pb),"__",fixed=TRUE));samp<-data.frame(donor_id=factor(sm[,1]),GART_status=factor(sm[,2],levels=c("negative","positive")));rownames(samp)<-colnames(pb);y<-DGEList(pb,samples=samp);keep<-filterByExpr(y,group=samp$GART_status,min.count=10);y<-y[keep,,keep.lib.sizes=FALSE];y<-calcNormFactors(y);design<-model.matrix(~donor_id+GART_status,samp);y<-estimateDisp(y,design,robust=TRUE);fit<-glmQLFit(y,design,robust=TRUE);tt<-topTags(glmQLFTest(fit,coef="GART_statuspositive"),n=Inf,sort.by="none")$table;se<-abs(tt$logFC/qnorm(tt$PValue/2,lower.tail=FALSE));data.frame(gene=rownames(tt),logFC=tt$logFC,SE=se,CI_low=tt$logFC-1.96*se,CI_high=tt$logFC+1.96*se,raw_P=tt$PValue,FDR=tt$FDR,n_paired_donors=length(ok),cell_threshold=threshold,model="edgeR QL; design ~ donor_id + GART_status")}
pb_file<-file.path(output_root,"RESULTS","SCP259_primary_pseudobulk_DEG.csv");sens_file<-file.path(output_root,"RESULTS","SCP259_pseudobulk_threshold_sensitivity.csv");if(file.exists(pb_file)&&file.exists(sens_file)){pb20<-read.csv(pb_file);sens<-read.csv(sens_file)}else{pb20<-run_pb(20);write.csv(pb20,pb_file,row.names=FALSE);sens<-do.call(rbind,lapply(c(10,20,50),run_pb));write.csv(sens,sens_file,row.names=FALSE)}
write.csv(data.frame(cohort="GSE214695",status="not_estimable",reason="Only one donor met >=20 cells in both GART states; paired pseudobulk design is not estimable."),file.path(output_root,"RESULTS","GSE214695_pseudobulk_status.csv"),row.names=FALSE)
read_gmt<-function(path){x<-strsplit(readLines(path,warn=FALSE),"\t");setNames(lapply(x,function(v)unique(v[-c(1,2)])),vapply(x,`[` ,"",1))}
gmt_dir <- file.path(paths$external_data_root, "gene_sets", "msigdb")
invisible(lapply(file.path(gmt_dir, c("h.all.v2025.1.Hs.symbols.gmt", "c5.go.bp.v2025.1.Hs.symbols.gmt", "c2.cp.reactome.v2025.1.Hs.symbols.gmt")), gart_require_file, label = "MSigDB GMT file"));sets<-list(Hallmark=read_gmt(file.path(gmt_dir,"h.all.v2025.1.Hs.symbols.gmt")),GO_BP=read_gmt(file.path(gmt_dir,"c5.go.bp.v2025.1.Hs.symbols.gmt")),Reactome=read_gmt(file.path(gmt_dir,"c2.cp.reactome.v2025.1.Hs.symbols.gmt")))
ranks<-pb20$logFC;names(ranks)<-pb20$gene;ranks<-sort(ranks[is.finite(ranks)],decreasing=TRUE)
gsea_all<-list();for(coll in names(sets)){fg<-fgseaMultilevel(pathways=sets[[coll]],stats=ranks,minSize=15,maxSize=500,eps=1e-10,nproc=1);fg<-as.data.frame(fg);fg$leadingEdge<-vapply(fg$leadingEdge,paste,collapse="|",FUN.VALUE="");fg$collection<-coll;gsea_all[[coll]]<-fg}
gsea<-do.call(rbind,gsea_all);write.csv(gsea,file.path(output_root,"RESULTS","SCP259_primary_pseudobulk_GSEA.csv"),row.names=FALSE)
write.csv(data.frame(collection=c("Hallmark","GO_BP","Reactome"),source=c("MSigDB h.all v2025.1.Hs","MSigDB c5.go.bp v2025.1.Hs","MSigDB c2.cp.reactome v2025.1.Hs"),download_URL=c("https://data.broadinstitute.org/gsea-msigdb/msigdb/release/2025.1.Hs/h.all.v2025.1.Hs.symbols.gmt","https://data.broadinstitute.org/gsea-msigdb/msigdb/release/2025.1.Hs/c5.go.bp.v2025.1.Hs.symbols.gmt","https://data.broadinstitute.org/gsea-msigdb/msigdb/release/2025.1.Hs/c2.cp.reactome.v2025.1.Hs.symbols.gmt")),file.path(output_root,"AUDIT","GSEA_gene_set_sources.csv"),row.names=FALSE)
