# Public-release copy: file paths were converted to repository-relative paths.
# Statistical logic, parameters, thresholds, and seeds are unchanged from the archived final script.
script_dir <- dirname(normalizePath(sub("^--file=", "", grep("^--file=", commandArgs(), value=TRUE)[1]))); source(file.path(dirname(script_dir), "02_singlecell_preprocessing", "common.R"))
suppressPackageStartupMessages(library(SeuratObject))
m<-readRDS(gart_require_file(file.path(singlecell_root, "PSEUDOTIME_CORRECTED_CELL_METADATA.rds"), "frozen corrected pseudotime metadata"));m$cell_id_revision<-rownames(m)
sm<-do.call(rbind,lapply(split(m,paste(m$donor_id,m$GART_status,sep="||"),drop=TRUE),function(d)data.frame(donor_id=d$donor_id[1],cohort=d$cohort[1],condition=as.character(d$condition[1]),GART_status=as.character(d$GART_status[1]),n_cells=nrow(d),median_independent_root=median(d$pseudotime_independent_root,na.rm=TRUE),median_no_GART_no_cell_cycle=median(d$pseudotime_no_GART_no_cell_cycle,na.rm=TRUE))))
write.csv(sm,file.path(output_root,"RESULTS","pseudotime_donor_summary.csv"),row.names=FALSE)
metrics<-data.frame(metric=c("trajectory_rank_correlation","GART_correlation_independent_root","GART_correlation_cell_cycle_excluded"),estimate=c(cor(m$pseudotime_independent_root,m$pseudotime_no_GART_no_cell_cycle,method="spearman",use="complete.obs"),cor(m$pseudotime_independent_root,m$GART_expr_corrected,method="spearman",use="complete.obs"),cor(m$pseudotime_no_GART_no_cell_cycle,m$GART_expr_corrected,method="spearman",use="complete.obs")),n_cells=nrow(m),interpretation="Exploratory state-continuum localization; not temporal transition")
write.csv(metrics,file.path(output_root,"RESULTS","pseudotime_stability.csv"),row.names=FALSE)
pairs<-list();pairdat<-list();for(v in c("median_independent_root","median_no_GART_no_cell_cycle")){w<-reshape(sm[,c("donor_id","cohort","GART_status",v)],idvar=c("donor_id","cohort"),timevar="GART_status",direction="wide");neg<-paste0(v,".negative");pos<-paste0(v,".positive");w$delta<-w[[pos]]-w[[neg]];pairdat[[v]]<-data.frame(donor_id=w$donor_id,cohort=w$cohort,trajectory=v,negative=w[[neg]],positive=w[[pos]],delta=w$delta);tt<-t.test(w$delta);pairs[[v]]<-data.frame(trajectory=v,n_paired_donors=sum(is.finite(w$delta)),mean_delta=mean(w$delta,na.rm=TRUE),CI_low=tt$conf.int[1],CI_high=tt$conf.int[2],paired_t_P=tt$p.value,paired_Wilcoxon_P=wilcox.test(w$delta,exact=FALSE)$p.value)}
write.csv(do.call(rbind,pairs),file.path(output_root,"RESULTS","pseudotime_paired_donor_tests.csv"),row.names=FALSE);write.csv(do.call(rbind,pairdat),file.path(output_root,"RESULTS","pseudotime_paired_donor_data.csv"),row.names=FALSE)
root<-read.csv(gart_require_file(file.path(singlecell_root, "PSEUDOTIME_INDEPENDENT_ROOT_SELECTION.csv"), "frozen independent-root selection"));write.csv(root,file.path(output_root,"RESULTS","pseudotime_root_selection.csv"),row.names=FALSE)
obj<-readRDS(file.path(singlecell_root,"UC_GART_07_ISC_like_subclustered_FIXED_withDonor.rds"));u<-Embeddings(obj,"iscUMAP");pd<-data.frame(cell_id=rownames(u),UMAP1=u[,1],UMAP2=u[,2],m[rownames(u),c("GART_status","donor_id","cohort","condition","pseudotime_independent_root","pseudotime_no_GART_no_cell_cycle")]);write.csv(pd,file.path(output_root,"INTERMEDIATE","pseudotime_cell_plot_data.csv"),row.names=FALSE)
